services:
  - type: web
    name: college-erp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn college_management_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER
        value: true 